site_name: spellmatch

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.indexes
  - navigation.top
  icon:
    repo: fontawesome/brands/github
  custom_dir: docs/_overrides

plugins:
  - search
  - mkdocstrings:
      watch: 
      - spellmatch
      default_handler: python
      handlers:
        python:
          rendering:
extra:
  version:
    provider: mike

extra_css:
  - _stylesheets/mkdocstrings.css

copyright: Copyright &copy; 2022 Jonas Windhager

repo_url: https://github.com/BodenmillerGroup/spellmatch

nav:
  - index.md
  - Reference: reference/index.md
