site_name: spellmatch

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.expand
  - navigation.top
  icon:
    repo: fontawesome/brands/github
  custom_dir: docs/_overrides

plugins:
  - search
  - mermaid2:
      version: 8.6.4
      arguments:
        securityLevel: 'loose'
  - mkdocstrings:
      watch: 
      - spellmatch
      default_handler: python

extra:
  generator: false
  version:
    provider: mike

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true

extra_css:
  - _stylesheets/mkdocstrings.css

extra_javascript:
     - https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js

copyright: Copyright &copy; 2022 Jonas Windhager

repo_url: https://github.com/BodenmillerGroup/spellmatch

nav:
  - Documentation:
    - index.md
    - installation.md
    - Usage:
      - usage/index.md
      - usage/mask_alignment.md
      - usage/image_registration.md
      - usage/spatial_cell_matching.md
      - usage/cell_assignment.md
    - contributing.md
    - changelog.md
    - license.md
  - Algorithms:
    - algorithms/index.md
  - Benchmark:
    - benchmark/index.md
  - Reference:
    - reference/index.md
