site_name: spellmatch

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.expand
  - navigation.top
  icon:
    repo: fontawesome/brands/github
  custom_dir: docs/_overrides

plugins:
  - search
  - mkdocstrings:
      watch: 
      - spellmatch
      default_handler: python

extra:
  generator: false
  version:
    provider: mike

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true

extra_css:
  - _stylesheets/mkdocstrings.css

copyright: Copyright &copy; 2022 Jonas Windhager

repo_url: https://github.com/BodenmillerGroup/spellmatch

nav:
  - Documentation:
    - index.md
    - install.md
    - Usage:
      - usage/intro.md
      - usage/registration.md
      - usage/matching.md
    - contributing.md
    - changelog.md
    - license.md
  - Reference:
    - reference/index.md
