name: docs

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements_docs.txt
      - name: Build documentation (latest)
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin gh-pages
          mike deploy -u -p latest
      - name: Build documentation (versioned)
        if: startsWith(github.ref, 'refs/tags')
        run: 
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin gh-pages
          mike deploy -p ${GITHUB_REF#refs/tags/}
